### ISSUE TITLE
banner overflow

### ISSUE THREAD

**Issue by ValentinGratz** [andersnoren/oaknut#1]
Small report on the use of the theme, and mainly the banner widget.

When using the banner, an overflow appears at the bottom of the page.
Can't edit CSS like other themes.

Applying 
```
body, html { overflow-x: hidden !important; } 
```

(via a css snippet extension doesn't work.)

Would it be possible to enable CSS customization?

Thanks

The only solution is simply to put the banner as an image.

**Comment by andersnoren** [comment]
@ValentinGratz WordPress hides the Customizer when a block theme is active, so there's nothing in Oaknut specifically that disables it. You can still access the Customizer though – WordPress just hides the menu item. 

Go to yourdomain.com/wp-admin/customize.php, and you'll get the regular Customizer view with the Custom CSS panel.
