### ISSUE TITLE
Ability to add links

### ISSUE THREAD

**Issue by ValentinGratz** [andersnoren/oaknut#2]
I just tried to copy/paste the block to add links in addition to the 5 possible.
Unfortunately it doesn't work.

When I try to put the block in "reusable" to copy/paste it, in fact the texts change on all the blocks by displaying the same one.

This amounts to cloning the block without being able to modify anything without the modifications affecting the other blocks.

Example :

Link 1
Link 2
Link 3

Link 1
Link 2
Link 3

Can't do it this way:

Link 1
Link 2
Link 3

Link A
Link B
Link D

**Comment by andersnoren** [comment]
@ValentinGratz You create additional links by going to Appearance → Editor, click the text in the last button, and then do a line break. That will create another link at the bottom of the list.
